import { Resume } from '../src/app/core/models/resume.models';

export const PROFILE_CONFIG: Resume = {
  profilePicturePath: 'profile-picture.jpg',
  name: 'Yankel Scialom',
  title: 'Delivery Manager',
  summary:
    "Très tôt, j’ai ciblé la conception et le développement d'applications évoluant en environnement à fortes contraintes comme protagonistes de mon métier idéal ; j’apprécie en effet relever des défis. Mes derniers projets professionnels ont été une confirmation en ce sens ; il m'ont de surcroît permis d'identifier ce que je considère comme les trois piliers du système informatique contraint sur lequel j'aime travailler : la performance, la stabilité, la cohérence des données. J'ai pu me former et expérimenter à concevoir et développer autant dans le milieu du système embarqué, de l'application militaire comme financière.",
  email: 'yankel-pro@scialom.org',
  phone: '',
  website: 'https://www.linkedin.com/in/yankel-scialom',
  location: 'Châtillon, Île-de-France, France',

  experiences: [
    {
      title: 'Practice Leader Dev & Lead Delivery',
      company: 'CAPFI',
      location: 'Paris, France',
      startDate: '2025-03',
      endDate: 'Present',
      description: [
        'Cloud services, safely hosted at home.',
        'PiNanas is a private cloud platform with a wild range of services included.',
        'Built with security and ease of use in mind, empowering users to transform hardware into a homelab.',
      ],
    },
    {
      title: 'Release Manager — Capfi',
      company: 'Crédit Agricole CIB',
      location: 'Montrouge, Île-de-France, France',
      startDate: '2023-06',
      endDate: '2025-03',
      description: [
        "Release Manager d'Orchestrade pour CACIB ainsi que des ses logiciels et services annexes.",
        'Stratégie de release : objectif qualité maximale & time-to-market minimal.',
        "Culture : promotion de la responsabilisation par l'implication de tous aux prises de décisions.",
        'Processus : du développement au déploiement en accord avec notre stratégie et notre culture.',
        'Animation : synchronisation et accompagnement des 15 équipes de développement.',
        'Priorisation : stabilité vs urgence vs cas et projets particuliers.',
      ],
    },
    {
      title: 'Chef de projet — Capfi Technology',
      company: 'Société Générale',
      location: 'Paris et périphérie',
      startDate: '2022-05',
      endDate: '2023-05',
      description: [
        'Project Manager des projets issues de la redéfinition de la stratégie SOC de la Société Générale.',
        "Études d'opportunités.",
        'Cadrage, lancement, suivi et clôture des projets de transformation.',
        "Appels d'offre.",
        "Management transverse d'équipes.",
        "Gestion des budgets (millions d'euros pour 2023).",
      ],
    },
    {
      title: 'Chef de projets, Agile Master — Capfi Technology',
      company: 'Natixis Corporate & Investment Banking',
      location: 'Paris, France',
      startDate: '2019-05',
      endDate: '2022-04',
      description: [
        'Chef de projets techniques.',
        'Release Management : planification, suivi, communication.',
        "Création et évolutions d'infrastructures : priorisation, planification & suivi des développements.",
        "Mise en place d'une nouvelle technologie de grille de calcul distribué chez Natixis : GridGain.",
        'Scrum Master : Respect de SAFe et Scrum (PI, Sprint planning, rétro...).',
        'Stack: Scala/Java, C++, Python, Kafka, Jenkins, XL Deploy, GridGain, PostgreSQL.',
      ],
    },
    {
      title: 'Tech lead, Scrum Master — Capfi Technology',
      company: 'Ingenico',
      location: 'Paris, France',
      startDate: '2018-03',
      endDate: '2019-05',
      description: [
        "Scrum Master : Kickoff Scrum de l'équipe, Sensibilisation et suivi des membres de l'équipe, Accompagnement du PO.",
        'Tech lead : Modernisation des outils de développement (svn -> git, C++98 -> C++14, Redhat 5 -> 7).',
        "Mise en place de l'intégration continue (Jenkins, GitLab CI) et Docker.",
        'Stack: RedHat, C++14, PostgreSQL, Docker.',
      ],
    },
    {
      title: 'Développeur C++ industriel — Capfi Technology',
      company: 'STET',
      location: 'Puteaux, La Défense',
      startDate: '2015-01',
      endDate: '2018-02',
      description: [
        "Conception et développement d'applications bancaires temps-réel à haute disponibilité : Apple Pay & Paylib.",
        "Intégration d'Apple Pay dans le réseau d'autorisation bancaire français.",
        'Développement C++98 du TSP. Secure Coding.',
        'Profiling des applications : performance, memory leaks.',
        'Stack: C++98, Redhat Linux, Multithreading, TCP.',
      ],
    },
    {
      title: 'Ingénieur logiciel Sophis — Capfi Technology',
      company: 'Tikehau Capital',
      location: 'Paris VIII',
      startDate: '2014-07',
      endDate: '2015-01',
      description: [
        'Chef de projet : Sophis Toolkit lua, Outil de diagnostic automatique.',
        'Développeur : Toolkit Sophis, reverse-engineering, développement de nouvelles colonnes.',
        'Stack: C++, C#, SQL, Lua, Sophis Toolkit, Oracle.',
      ],
    },
    {
      title: 'Ingénieur conception logicielle',
      company: 'ThalesRaytheonSystems',
      location: 'Massy',
      startDate: '2013-05',
      endDate: '2014-07',
      description: [
        'Développeur logiciel C++/Java : Conception, développement et intégration de fonctionnalités IHM.',
        'Manager de centre de service : Assistant au directeur de projet.',
        'Stack: C++, Java, Perl, Solaris, ClearCase.',
      ],
    },
  ],
  educations: [
    {
      degree: "Diplôme d'ingénieur, Technologies mobiles et systèmes embarqués",
      institution: 'Université de Technologie de Troyes',
      location: 'Troyes, France',
      startDate: '2006',
      endDate: '2012',
    },
    {
      degree: 'Physics (Continuing Studies)',
      institution: 'Stanford University',
      location: 'Online',
      startDate: '2012',
      endDate: '2013',
    },
  ],
  skills: [
    { name: 'Français', level: 5 },
    { name: 'Anglais', level: 5 },
    { name: 'Allemand', level: 2 },
    { name: 'C++', level: 5 },
    { name: 'Java', level: 4 },
    { name: 'Python', level: 4 },
    { name: 'Docker', level: 4 },
    { name: 'Kubernetes', level: 3 },
    { name: 'CI/CD', level: 4 },
    { name: 'Agile/Scrum', level: 5 },
    { name: 'SAFe', level: 4 },
    { name: 'SQL', level: 4 },
    { name: 'Linux', level: 4 },
  ],
};
