const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const outputDir = path.join(__dirname, '../src/app/core');
const outputFile = path.join(outputDir, 'version.ts');

let version = 'unknown';
const versionArg = process.argv.find((arg) => arg.startsWith('--version='));

if (versionArg) {
  version = versionArg.split('=')[1];
} else {
  try {
    version = execSync('git describe --tags --always', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch (e) {
    version = process.env['APP_VERSION'] || 'v0.0.0';
  }
}

const content = `// This file is auto-generated by tools/generate-version.js
export const VERSION = '${version}';
`;

if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputFile, content);
console.log(`Generated ${outputFile} with version: ${version}`);
