// This file is auto-generated by tools/generate-profile-registry.js
import { Resume } from './models/resume.models';
// @ts-expect-error - Profile files are outside src directory
import { PROFILE_CONFIG as en_US } from '../../../config/profile.en_US';
// @ts-expect-error - Profile files are outside src directory
import { PROFILE_CONFIG as fr_FR } from '../../../config/profile.fr_FR';

export const PROFILES: Record<string, Resume> = {
  'en_US': en_US,
  'fr_FR': fr_FR,
};

export const SUPPORTED_LANGUAGES = ['en_US', 'fr_FR'];
